//
//  EventsEnum.swift
//  AwsFreertos
//
//  Created by Franco Roberti on 15/04/2021.
//  Copyright © 2021 Facebook. All rights reserved.
//

import Foundation

enum EventsEnum: String {
    case DID_UPDATE_BLE_POWER_STATE = "DID_UPDATE_BLE_POWER_STATE"
    case DID_DISCONNECT_DEVICE = "DID_DISCONNECT_DEVICE"
    case DID_DISCOVERED_DEVICE = "DID_DISCOVERED_DEVICE"
    case DID_CONNECT_DEVICE = "DID_CONNECT_DEVICE"
    case DID_FAIL_TO_CONNECT_DEVICE = "DID_FAIL_TO_CONNECT_DEVICE"
    case DID_READ_CHARACTERISTIC_FROM_SERVICE = "DID_READ_CHARACTERISTIC_FROM_SERVICE"
    case DID_LIST_NETWORK = "DID_LIST_NETWORK"
    case DID_SAVE_NETWORK = "DID_SAVE_NETWORK"
    case DID_EDIT_NETWORK = "DID_EDIT_NETWORK"
    case DID_DELETE_NETWORK = "DID_DELETE_NETWORK"
}
