# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AwsFreertos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AwsFreertos

  pod 'AmazonFreeRTOS', :path => './amazon-freertos-ble-ios-sdk-master'
  pod 'AWSAuthUI'
  pod 'AWSMobileClient','~> 2.17.0'
  pod 'AWSUserPoolsSignIn'
  pod 'LicensePlist'
  pod 'SwiftFormat/CLI'
  pod 'SwiftLint'
end
