package com.reactnativeawsfreertos

enum class BluetoothEvents {
  DID_UPDATE_BLE_POWER_STATE,
  DID_DISCONNECT_DEVICE,
  DID_DISCOVERED_DEVICE,
  DID_CONNECT_DEVICE,
  DID_FAIL_TO_CONNECT_DEVICE,
  DID_READ_CHARACTERISTIC_FROM_SERVICE
}
