package com.reactnativeawsfreertos

/**
  *This GATT service distributes security token values generated by WiFi Module.
 * GATT service UUID is ad3cee4a-c6d0-4b38-aed6-5459813c5847
**/

enum class GattUUID(val uuid: String) {
  /** This characteristic displays a security token to be used to bind together user account in mobile app and physical device.
   * Characteristic is read-only and can be accessed only after successful BLE pairing (no unauthorized access allowed).
   * BLE notifications for this characteristic are available as well.
  **/
  ACCOUNT_BINDING_TOKEN_CHARACTERISTIC("35eeb3ed-80b2-437d-9f80-e673ca2bea45"),
  /**
  *  This characteristic displays a device serial number (the same one which is used during device provisioning procedure).
  * Characteristic is read-only and can be accessed only after successful BLE pairing (no unauthorized access allowed).
  * BLE notifications for this characteristic are not available since this
  * characteristic’s value is not expected to be changed over lifetime of the device. Device serial number value
  * is ASCII-coded string. The value is  null-terminated, use BLE data length property to determine string length.
  **/
  DEVICE_SERIAL_NUMBER_CHARACTERISTIC("38c4fb0f-b43b-493f-94a1-1634cbc9d66f"),
  /**
   * This characteristic displays device provisioning status.
   * Characteristic is read-only and can be accessed only after successful BLE pairing (no unauthorized access allowed).
   * BLE notifications for this characteristic are available as well. Device provisioning status is one byte value.
   * Zero indicates device is not provisioned yet.
   * Non-zero value (typically it is set to one, but you should not rely on this)
   * means device is fully provisioned to the cloud.
   **/
  DEVICE_PROVISIONING_STATUS_CHARACTERISTIC("693e440d-65bf-4f62-ba23-2319b2bc42b6")
}
